const groq = require("../services/ai/providers/groq");

/**
 * TECHNICAL AUDITOR - NOCTUA V4 (AI SAFETY LAYER)
 * Audit final technical payloads generated by deterministic rules.
 */

const REQUIRED_FIELDS = [
  "profile",
  "system_type",
  "estimated_cable_total_m",
  "resolved_items"
];

const SYSTEM_PROMPT = `
Você é o Engenheiro Sênior de Segurança Eletrônica da NOCTUA. 
Sua missão: Auditar a viabilidade técnica do payload gerado pelo sistema.

REGRAS DE OURO:
1. O PAYLOAD É A VERDADE: Julgue os itens presentes na lista "items". Se houver 4 câmeras no payload, o projeto tem 4 câmeras, ponto final.
2. CAPACIDADE NOMINAL: 4 câmeras em gravador de 4 canais (ou 8 em 8, 16 em 16) é PERFEITO. Não sinalize como suspeito.
3. STORAGE: IP consome 25GB/dia/câmera. Analog consome 15GB/dia/câmera. Use isso para checar o HD.
4. MODELO B (MÃO DE OBRA): Se o modelo for "B", o hardware é do cliente. Falhas de capacidade (ex: NVR subdimensionado) não são falhas da NOCTUA. Relate apenas como observação de risco técnico, NUNCA como se fosse erro de dimensionamento nosso.
5. JSON ESTRITO: Sua resposta deve ser apenas o objeto JSON. Proibido usar ":" dentro de arrays de strings. Use apenas descrições simples nas evidências.

RESPOSTA (JSON):
{
  "audit_state": "APPROVED | SUSPECT | MANDATORY_REVIEW | BLOCKED",
  "ai_observations": "Texto direto.",
  "flags": [
    {
      "severity": "LOW | MEDIUM | HIGH | CRITICAL",
      "issue": "Problema.",
      "field": "Campo.",
      "evidence": ["Texto simples sem aspas extras ou dois pontos"]
    }
  ],
  "recommendation": "Ação.",
  "missing_fields": []
}
`;

class TechnicalAuditor {
  async audit(session, payload) {
    let rawResponse = "";
    try {
      // 1. Validar campos críticos
      const missing = REQUIRED_FIELDS.filter(f => !payload[f]);
      if (missing.length > 0) return this.getIncompleteResponse(missing);

      // 2. Contexto simplificado (evita confusão de contagem)
      const context = {
        meta: {
          modelo: session.budget_model, // A, B ou C
          perfil: payload.profile,
          tecnologia: payload.system_type,
          ambiente: session.installation_environment,
          dias_gravacao: session.technical_scope?.recording_days || 15
        },
        payload: {
          distancia_max_m: payload.max_point_distance_m,
          cabo_total_m: payload.estimated_cable_total_m,
          itens: payload.resolved_items?.map(i => `${i.qtd}x ${i.produto} (${i.categoria})`)
        }
      };

      // 3. Chamar IA
      rawResponse = await groq.execute(JSON.stringify(context), SYSTEM_PROMPT);

      // 4. Parsing
      return this.parseResponse(rawResponse);

    } catch (error) {
      console.error("[Technical Auditor Error]:", error.message);
      return this.getFallbackResponse("Erro de processamento.");
    }
  }

  parseResponse(text) {
    try {
      const jsonMatch = text.match(/\{[\s\S]*\}/);
      let jsonStr = jsonMatch ? jsonMatch[0] : text;
      
      // Limpeza agressiva para corrigir JSON malformado comum em IAs
      jsonStr = jsonStr.replace(/\\"/g, '"').replace(/": /g, '":');
      
      const parsed = JSON.parse(jsonStr);
      return {
        audit_state: parsed.audit_state || "MANDATORY_REVIEW",
        ai_observations: parsed.ai_observations || "Auditoria concluída.",
        flags: Array.isArray(parsed.flags) ? parsed.flags : [],
        recommendation: parsed.recommendation || "Validar itens manualmente.",
        missing_fields: []
      };
    } catch (e) {
      console.log("[IA Parsing Failure] Raw:", text);
      return this.getFallbackResponse("Erro de sintaxe na resposta da IA.");
    }
  }

  getIncompleteResponse(missing) {
    return {
      audit_state: "MANDATORY_REVIEW",
      ai_observations: "Dados insuficientes.",
      flags: [{ severity: "HIGH", issue: "Payload incompleto", field: "payload", evidence: missing }],
      recommendation: "Completar dados técnicos.",
      missing_fields: missing
    };
  }

  getFallbackResponse(reason) {
    return {
      audit_state: "MANDATORY_REVIEW",
      ai_observations: `Auditoria indisponível: ${reason}`,
      flags: [{ severity: "MEDIUM", issue: "Fail-Safe", field: "system", evidence: [reason] }],
      recommendation: "Revisão manual obrigatória.",
      missing_fields: []
    };
  }
}

module.exports = new TechnicalAuditor();
