name: Noctua CI/CD

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    name: "Deploy no Servidor Local"
    runs-on: self-hosted  # ISSO MANDA PARA SUA VM
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Resetar Permissões (Opcional)
        run: sudo chown -R github-runner:github-runner .

      - name: Build e Deploy com Docker
        run: |
          if [ -f "docker-compose.yml" ]; then
            docker compose up -d --build --remove-orphans
          else
            echo "ERRO: docker-compose.yml não encontrado na raiz do projeto!"
            exit 1
          fi